### PR TITLE
fix(monitoring): disable monitoring until stable

### PR DESCRIPTION
**Pull request by rofe**

### CODE REVIEW

**Comment by trieloff** [comment]
I think this commit should fix it, too: https://github.com/adobe/helix-query-index/commit/c2156c3311e90d9741c0b23b08fea337ed22f79e

**Comment by trieloff** [comment]
https://adobeioruntime.net/api/v1/web/helix/helix-services/query-index@v1.1/_status_check/healthcheck.json is now returning something meaningful.

**Comment by trieloff** [comment]
New Relic reports the service being up now.

**Comment by rofe** [comment]
Ok... I would probably still move it to Development until we're more confident and use it productively

**Pull request closed without merging**
